version: 0.0
os: linux
files:
  - source: dist/
    destination: /home/ec2-user/
hooks:
  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user