version: '3.7'

services:
  database:
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_USER: user
    ports:
      - 5432:5432

volumes:
  database-storage:
