entryPoints:
  web:
    address: :80
  websecure:
    address: :443
certificatesResolvers:
  letsencrypt:
    acme:
      email: chutiponh@hotmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
providers:
  file:
    filename: ./backend.yaml
api:
  insecure: true
  dashboard: true
